# Generated by Django 4.1.1 on 2023-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=10, null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=1000, null=True)),
                ('tax', models.FloatField(max_length=100, null=True)),
                ('amount', models.FloatField(max_length=100, null=True)),
            ],
        ),
    ]
