# Generated by Django 4.1.1 on 2023-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_alter_invoice_amount_alter_invoice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
