# Generated by Django 4.1.1 on 2023-04-29 10:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_invoice_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='json',
            new_name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='prices',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantities',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
