# Generated by Django 4.1.1 on 2023-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_rename_json_invoice_items_invoice_prices_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
