# Generated by Django 4.1.1 on 2023-04-29 13:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_delete_items_invoice_amount_invoice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
