# Generated by Django 4.1.1 on 2023-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0009_add_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_items',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='add_items',
            name='tax',
        ),
        migrations.AddField(
            model_name='add_items',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
