# Generated by Django 4.1.1 on 2023-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0010_remove_add_items_amount_remove_add_items_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
